### ISSUE TITLE
Question: Is there no support for bulk $import if I want to upload files from my local machine?

### ISSUE THREAD

**Issue by jordanperrin** [smart-on-fhir/bulk-import#15]

**Comment by jmandel** [comment]
This repository contains a protocol specification; your question appears to be about implementations (e.g., servers supporting the spec). You'll want to post this question for whoever maintains the server that you're trying to talk to.

**Comment by jordanperrin** [comment]
Ah my bad I thought I was in the IBM FHIR Repo for some reason, thank you for the response.
